add new relic to TD and workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -100,6 +100,30 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
 
+      - name: Download New Relic Java Agent
+        run: |
+          mkdir -p newrelic
+          curl -o newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-agent.jar
+
+      - name: Verify New Relic Agent location
+        run: |
+          if [ -f newrelic/newrelic.jar ]; then
+            echo "New Relic Agent found at newrelic/newrelic.jar"
+          else
+            echo "New Relic Agent NOT found!"
+            exit 1
+          fi
+
+      - name: Configure New Relic
+        run: |
+          echo "common: &default_settings
+            license_key: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
+            app_name: '${{ vars.NEW_RELIC_APP_NAME }}-${{ github.event.inputs.environment }}'
+            distributed_tracing:
+              enabled: true
+            logging:
+              level: debug" > newrelic/newrelic.yml
+
       - name: Build image
         id: build-image
         env:
