add new relic to TD and workflow

diff --git a/.github/workflows/deploy_service.yml b/.github/workflows/deploy_service.yml
--- a/.github/workflows/deploy_service.yml
+++ b/.github/workflows/deploy_service.yml
@@ -47,6 +47,16 @@ jobs:
           mkdir -p newrelic
           curl -o newrelic/newrelic.jar https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-agent.jar
 
+      - name: Verify New Relic Agent location
+        run: |
+          # Проверим, что файл агента действительно скачан
+          if [ -f newrelic/newrelic.jar ]; then
+            echo "New Relic Agent found at newrelic/newrelic.jar"
+          else
+            echo "New Relic Agent NOT found!"
+            exit 1
+          fi
+
       - name: Configure New Relic
         run: |
           echo "common: &default_settings
