rename

diff --git a/.github/workflows/terraform_deploy.yml b/.github/workflows/terraform_deploy.yml
--- a/.github/workflows/terraform_deploy.yml
+++ b/.github/workflows/terraform_deploy.yml
@@ -43,6 +43,14 @@ jobs:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
 
+    - name: Select .tfvars file based on environment
+      run: |
+        echo "Selecting .tfvars file for environment: ${{ github.event.inputs.environment }}"
+        if [[ ! -f "${{ env.working-directory }}/${{ github.event.inputs.environment }}.tfvars" ]]; then
+          echo "Error: File ${{ github.event.inputs.environment }}.tfvars does not exist in ${{ env.working-directory }}."
+          exit 1
+        fi
+
     - name: Terraform Init
       run: terraform init
 
@@ -50,7 +58,7 @@ jobs:
       run: terraform fmt -check
 
     - name: Terraform Plan
-      run: terraform plan -input=false
+      run: terraform plan -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
 
-    - name: Terraform apply
-      run: terraform apply -auto-approve -input=false
+    - name: Terraform Apply
+      run: terraform apply -auto-approve -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
